wandb_version: 1

activation:
  value: Sigmoid
batch_size:
  value: 32
epochs:
  value: 5
initializer:
  value: he
learning_rate:
  value: 0.0001
num_hidden_neurons:
  value: 128
num_layers:
  value: 4
optimizer:
  value: Adam
weight_decay:
  value: 0
