wandb_version: 1

activation:
  value: Sigmoid
batch_size:
  value: 32
epochs:
  value: 5
initializer:
  value: he
learning_rate:
  value: 0.001
num_hidden_neurons:
  value: 64
num_layers:
  value: 4
optimizer:
  value: SGD
weight_decay:
  value: 0.5
