wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
epochs:
  value: 5
initializer:
  value: random
learning_rate:
  value: 0.0001
num_hidden_neurons:
  value: 32
num_layers:
  value: 5
optimizer:
  value: Adam
weight_decay:
  value: 0.0005
