wandb_version: 1

activation:
  value: Tanh
batch_size:
  value: 16
epochs:
  value: 10
initializer:
  value: xavier
learning_rate:
  value: 0.001
num_hidden_neurons:
  value: 32
num_layers:
  value: 5
optimizer:
  value: Adam
weight_decay:
  value: 0.0005
