wandb_version: 1

activation:
  value: Tanh
batch_size:
  value: 16
epochs:
  value: 5
initializer:
  value: xavier
learning_rate:
  value: 0.0001
num_hidden_neurons:
  value: 128
num_layers:
  value: 5
optimizer:
  value: SGD
weight_decay:
  value: 0.5
