wandb_version: 1

activation:
  value: Sigmoid
batch_size:
  value: 64
epochs:
  value: 10
initializer:
  value: he
learning_rate:
  value: 0.001
num_hidden_neurons:
  value: 32
num_layers:
  value: 5
optimizer:
  value: Nadam
weight_decay:
  value: 0.0005
