wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
epochs:
  value: 10
initializer:
  value: xavier
learning_rate:
  value: 0.001
num_hidden_neurons:
  value: 64
num_layers:
  value: 4
optimizer:
  value: RMSprop
weight_decay:
  value: 0
