wandb_version: 1

activation:
  value: Tanh
batch_size:
  value: 64
epochs:
  value: 10
initializer:
  value: xavier
learning_rate:
  value: 0.001
num_hidden_neurons:
  value: 128
num_layers:
  value: 4
optimizer:
  value: Nadam
weight_decay:
  value: 0
