wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
epochs:
  value: 10
initializer:
  value: he
learning_rate:
  value: 0.001
num_hidden_neurons:
  value: 64
num_layers:
  value: 4
optimizer:
  value: Adam
weight_decay:
  value: 0
