wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
epochs:
  value: 10
initializer:
  value: he
learning_rate:
  value: 0.0001
num_hidden_neurons:
  value: 128
num_layers:
  value: 4
optimizer:
  value: Nadam
weight_decay:
  value: 0
