wandb_version: 1

activation:
  value: Tanh
batch_size:
  value: 64
epochs:
  value: 5
initializer:
  value: he
learning_rate:
  value: 0.001
num_hidden_neurons:
  value: 32
num_layers:
  value: 4
optimizer:
  value: RMSprop
weight_decay:
  value: 0
