wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
epochs:
  value: 5
initializer:
  value: random
learning_rate:
  value: 0.001
num_hidden_neurons:
  value: 128
num_layers:
  value: 4
optimizer:
  value: SGD
weight_decay:
  value: 0.5
