wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
epochs:
  value: 5
initializer:
  value: xavier
learning_rate:
  value: 0.001
num_hidden_neurons:
  value: 128
num_layers:
  value: 3
optimizer:
  value: Adam
weight_decay:
  value: 0
