wandb_version: 1

activation:
  value: Tanh
batch_size:
  value: 16
epochs:
  value: 10
initializer:
  value: he
learning_rate:
  value: 0.0001
num_hidden_neurons:
  value: 128
num_layers:
  value: 3
optimizer:
  value: Nadam
weight_decay:
  value: 0.001
