wandb_version: 1

activation:
  value: Sigmoid
batch_size:
  value: 16
epochs:
  value: 10
initializer:
  value: he
learning_rate:
  value: 0.001
num_hidden_neurons:
  value: 64
num_layers:
  value: 4
optimizer:
  value: NAG
weight_decay:
  value: 0
