wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
epochs:
  value: 5
initializer:
  value: xavier
learning_rate:
  value: 0.0005
num_hidden_neurons:
  value: 128
num_layers:
  value: 3
optimizer:
  value: Nadam
weight_decay:
  value: 0.001
