wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1645781161
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
    visualize:
      conf_mat:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: conf_mat_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
activation:
  desc: null
  value: ReLU
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 10
initializer:
  desc: null
  value: he
learning_rate:
  desc: null
  value: 0.0001
num_hidden_neurons:
  desc: null
  value: 128
num_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: Adam
weight_decay:
  desc: null
  value: 0
