wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1645698999
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      4: 3.9.7
      5: 0.12.10
      8:
      - 1
      - 5
activation:
  desc: null
  value: ReLU
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 5
initializer:
  desc: null
  value: random
learning_rate:
  desc: null
  value: 0.001
num_hidden_neurons:
  desc: null
  value: 32
num_layers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: Adam
weight_decay:
  desc: null
  value: 0
