wandb_version: 1

activation:
  value: Tanh
batch_size:
  value: 64
epochs:
  value: 10
initializer:
  value: random
learning_rate:
  value: 0.0001
num_hidden_neurons:
  value: 64
num_layers:
  value: 5
optimizer:
  value: RMSprop
weight_decay:
  value: 0.0005
