wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
epochs:
  value: 5
initializer:
  value: he
learning_rate:
  value: 0.0001
num_hidden_neurons:
  value: 128
num_layers:
  value: 3
optimizer:
  value: RMSprop
weight_decay:
  value: 0.05
